services:
  - type: web
    name: sba-risk-engine
    env: python
    region: ohio
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:server
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: DATABASE_URL
        sync: false # Tells Render not to expose your password in this public file